### ISSUE TITLE
fd_numpy return type

### ISSUE THREAD

**Issue by yck011522** [compas-ITA19/ITA19#4]
In assignment Module 1 Week 1 we need to use something like this.

xyz, q, f, l, r = numerical.fd_numpy(xyz, edges, fixed, q, loads)

According to [documentation](https://github.com/compas-dev/compas/blob/master/src/compas/numerical/fd/fd_numpy.py), f, l and r should be an array of results. I assume it should be an one level list. However, the actual result is a list of list of values. The inner list all has only one item in it.

Is this the correct behavior? Is there a situation where there are more than one item in this inner list?

**Comment by tomvanmele** [comment]
hi viktor,

that is the result of the automatic conversion from `numpy` to `python` performed by the RPC system. in `numpy` `q`, `f` and `l` are arrays (or matrices) of size `mx1` with `m` the number of edges in the data structure. so technically, they have `m` rows with only 1 column, which translates to a list of lists with each only one element.

so, yes, it is correct, but i can see how that can be confusing and will try to address this in the docs...

**Comment by yck011522** [comment]
Hi Tom, Thanks. Got it.
